// var angular = require('./public/javascripts/angular/angular.js')
// var request = require('./node_modules/browser-request/index.js')
// var ngTable = require('./node_modules/ng-table/dist/ng-table.js')
// var firebase = require('./public/javascripts/firebase/firebase.js')
// require('./public/javascripts/angular-css/angular-css.js')
// require('./node_modules/angular-ui-router/release/angular-ui-router.js')
// var app = require('./public/javascripts/app.js')
// var appRoutes = require('./public/javascripts/appRoutes.js')
// var angularfire = require('./public/javascripts/angularfire/dist/angularfire.js')
// var angModal = require('./public/javascripts/services/angModal.js')
// var chatSocket = require('./public/javascripts/services/chatSocket.js')
// var ctrlShare = require('./public/javascripts/services/ctrlShare.js')
// var ranFactory = require('./public/javascripts/services/ranFactory.js')
// var testDir  = require('./public/javascripts/services/testDir.js')
// var modal = require('./public/javascripts/angular-modal/modal.js')
// var fireBaseController = require('./public/javascripts/controllers/fireBaseController.js')
// var homeController = require('./public/javascripts/controllers/homeController.js')
// var chatController = require('./public/javascripts/controllers/chatController.js')
// var cheerio = require('./node_modules/cheerio/lib/cheerio.js')
// var angular = require('angular')
// var request = require('browser-request')
// var cheerio = require('./node_modules/cheerio/lib/cheerio.js')
// var ngTable = require('./node_modules/ng-table/dist/ng-table.js')
// var firebase = require('./public/javascripts/firebase/firebase.js')
// require('./public/javascripts/angular-css/angular-css.js')
// require('./node_modules/angular-ui-router/release/angular-ui-router.js')
// require('./public/javascripts/req.js');
// var app = require('./public/javascripts/app.js')
// var appRoutes = require('./public/javascripts/appRoutes.js')
// var angularfire = require('./public/javascripts/angularfire/dist/angularfire.js')
// var angModal = require('./public/javascripts/services/angModal.js')
// var chatSocket = require('./public/javascripts/services/chatSocket.js')
// var ctrlShare = require('./public/javascripts/services/ctrlShare.js')
// var ranFactory = require('./public/javascripts/services/ranFactory.js')
// var testDir  = require('./public/javascripts/services/testDir.js')
// var modal = require('./public/javascripts/angular-modal/modal.js')
// var fireBaseController = require('./public/javascripts/controllers/fireBaseController.js')
// var homeController = require('./public/javascripts/controllers/homeController.js')
// var chatController = require('./public/javascripts/controllers/chatController.js')
////
var angular = require('./node_modules/angular/angular.js')
require('./node_modules/socket.io-client/lib/socket.js')
require('./node_modules/angular-socket-io/socket.js')
require('./node_modules/socket.io-client/socket.io.js')
var request = require('browser-request')
var cheerio = require('./node_modules/cheerio/lib/cheerio.js')
var ngTable = require('./node_modules/ng-table/dist/ng-table.js')
var firebase = require('./public/javascripts/firebase/firebase.js')
require('./public/javascripts/angular-css/angular-css.js')
require('./node_modules/angular-ui-router/release/angular-ui-router.js')
var app = require('./public/javascripts/app.js')
var appRoutes = require('./public/javascripts/appRoutes.js')
var angularfire = require('./public/javascripts/angularfire/dist/angularfire.js')
var angModal = require('./public/javascripts/services/angModal.js')
var chatSocket = require('./public/javascripts/services/chatSocket.js')
var ctrlShare = require('./public/javascripts/services/ctrlShare.js')
var ranFactory = require('./public/javascripts/services/ranFactory.js')
var testDir  = require('./public/javascripts/services/testDir.js')
var modal = require('./public/javascripts/angular-modal/modal.js')
var fireBaseController = require('./public/javascripts/controllers/fireBaseController.js')
var homeController = require('./public/javascripts/controllers/homeController.js')
var chatController = require('./public/javascripts/controllers/chatController.js')
